author: Visually Enforced
description: Gaston Sanchez's blog about data analysis, applied statistics, R
url: http://gastonsanchez.com/visually-enforced
baseurl: http://gastonsanchez.com/visually-enforced
highlighter: rouge
permalink: pretty
markdown: kramdown
exclude: ["Rmd", ".DS_Store", "README.md"]
excerpt_separator: <!--more-->